/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "tertiary": "#5e5e62",
        "outline": "#7e7761",
        "status-warning": "#F9A825",
        "secondary-container": "#e0dfe1",
        "on-error-container": "#93000a",
        "outline-variant": "#cfc6ac",
        "on-secondary-container": "#626265",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c7c6c8",
        "primary-fixed": "#ffe16e",
        "surface-container": "#eeeeee",
        "on-surface": "#1a1c1c",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#c7c6ca",
        "secondary": "#5e5e60",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed": "#e3e2e6",
        "primary": "#705d00",
        "on-tertiary-fixed-variant": "#46474a",
        "secondary-fixed": "#e3e2e4",
        "status-error": "#D32F2F",
        "inverse-primary": "#e8c41d",
        "primary-container": "#fdd835",
        "status-info": "#0288D1",
        "inverse-on-surface": "#f1f1f1",
        "on-surface-variant": "#4c4733",
        "terminal-bg": "#1A1B1E",
        "surface-dim": "#dadada",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#dbdade",
        "primary-fixed-dim": "#e8c41d",
        "on-tertiary-fixed": "#1a1b1e",
        "surface-white": "#FFFFFF",
        "status-success": "#2D7D32",
        "on-error": "#ffffff",
        "on-primary-fixed": "#221b00",
        "background": "#f9f9f9",
        "on-secondary": "#ffffff",
        "terminal-text": "#E0E0E0",
        "on-tertiary-container": "#5f5f63",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#464749",
        "on-primary-fixed-variant": "#544600",
        "on-primary-container": "#715e00",
        "surface-tint": "#705d00",
        "on-background": "#1a1c1c",
        "on-secondary-fixed": "#1a1c1d",
        "inverse-surface": "#2f3131",
        "surface-container-high": "#e8e8e8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "base": "4px",
        "max-width": "1200px",
        "md": "16px",
        "xs": "4px",
        "margin-mobile": "16px",
        "sm": "8px",
        "margin-desktop": "32px",
        "xl": "32px",
        "lg": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-bold": ["12px", { "lineHeight": "16px", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "code-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
